# Generated by Django 3.2.5 on 2022-01-18 12:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('registration_plate', models.CharField(max_length=15, unique=True)),
                ('fuel', models.CharField(max_length=10)),
                ('max_load', models.IntegerField()),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.TextField(max_length=25)),
                ('destination', models.TextField(max_length=25)),
                ('departure_date', models.DateField(default=datetime.datetime(2022, 1, 18, 12, 58, 56, 171914, tzinfo=utc))),
                ('arrival_date', models.DateField(default=datetime.datetime(2022, 1, 18, 12, 58, 56, 171914, tzinfo=utc))),
                ('max_price', models.FloatField(default=0)),
                ('freight_type', models.CharField(max_length=15)),
                ('weight', models.IntegerField()),
                ('phone', models.CharField(default='0', max_length=11)),
                ('email', models.CharField(default='a', max_length=50)),
                ('other_details', models.CharField(default='a', max_length=200)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('freight_type', models.CharField(max_length=15)),
                ('price_per_km', models.FloatField(default=0)),
                ('price_per_km_emptyTruck', models.FloatField(default=0)),
                ('departure_date', models.DateField(default=datetime.datetime(2022, 1, 18, 12, 58, 56, 171914, tzinfo=utc))),
                ('source', models.CharField(default='a', max_length=30)),
                ('arrival_date', models.DateField(default=datetime.datetime(2022, 1, 18, 12, 58, 56, 171914, tzinfo=utc))),
                ('destination', models.CharField(default='a', max_length=30)),
                ('phone', models.CharField(default='0', max_length=11)),
                ('email', models.CharField(default='a', max_length=50)),
                ('other_details', models.CharField(default='a', max_length=200)),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('truckID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.truck')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.TextField(max_length=25)),
                ('destination', models.TextField(max_length=25)),
                ('date', models.DateField(auto_now_add=True)),
                ('freight_type', models.TextField(max_length=15)),
                ('final_price', models.FloatField()),
                ('km', models.FloatField()),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('transporterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporter', to=settings.AUTH_USER_MODEL)),
                ('truckID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.truck')),
            ],
        ),
    ]
