# Generated by Django 4.0 on 2022-01-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='email',
        ),
        migrations.RemoveField(
            model_name='request',
            name='other_details',
        ),
        migrations.RemoveField(
            model_name='request',
            name='phone',
        ),
    ]
