# Generated by Django 4.0 on 2022-01-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_request_email_remove_request_other_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='other_details',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='phone',
            field=models.CharField(default='0', max_length=11),
        ),
    ]
