# Generated by Django 4.0 on 2022-01-12 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_request_registration_date_offer_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='arrival_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 12, 10, 51, 20, 754976, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='departure_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 12, 10, 51, 20, 754976, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='arrival_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 12, 10, 51, 20, 753979, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='departure_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 12, 10, 51, 20, 753979, tzinfo=utc)),
        ),
    ]
